// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aefmvlqldbypbqionlcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFlZm12bHFsZGJ5cGJxaW9ubGNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MjMyNTUsImV4cCI6MjA2MzQ5OTI1NX0.X8QsZN7lLJsVaLTM8rUI0PRzxqDYZjx3K9fwXQS2zPM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);